[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "oparl-cache"
version = "0.1.0"

[[bin]]
doc = false
name = "oparl-cache"

[dependencies]
chrono = "0.2.25"
clap = "2.18.0"
crossbeam = "0.2.10"
hyper = "0.9.12"
json = "0.11.0"
