[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "oparl-cache"
version = "0.1.0"

[[bin]]
doc = false
name = "oparl-cache"

[dependencies]
chrono = "^0.3.0"
clap = "^2.21.0"
crossbeam = "^0.2.0"
json = "^0.11.0"
reqwest = "0.4.0"
