[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "parlgen"
version = "0.1.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
reqwest = "0.8.0"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.4"
url = "1.5.1"
url_serde = "0.2.0"
